import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
	MatButtonModule,
	MatCardModule,
	MatCheckboxModule,
	MatChipsModule,
	MatDialogModule,
	MatExpansionModule,
	MatGridListModule,
	MatIconModule,
	MatInputModule,
	MatListModule,
	MatMenuModule,
	MatProgressBarModule,
	MatRadioModule,
	MatSelectModule,
	MatSidenavModule,
	MatSlideToggleModule,
	MatSnackBarModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule,
	MatTableModule,
} from "@angular/material";

@NgModule({
	imports: [
	    CommonModule,
		MatToolbarModule,
		MatSidenavModule,
		MatTabsModule,
		MatListModule,
		MatIconModule,
		MatSlideToggleModule,
		MatCardModule,
		MatButtonModule,
		MatMenuModule,
		MatDialogModule,
		MatSelectModule,
		MatInputModule,
		MatCheckboxModule,
		MatExpansionModule,
		MatRadioModule,
		MatGridListModule,
		MatSnackBarModule,
		MatProgressBarModule,
		MatChipsModule,
		MatTooltipModule,
		MatTableModule
	],
	exports: [
		MatToolbarModule,
		MatSidenavModule,
		MatTabsModule,
		MatListModule,
		MatIconModule,
		MatSlideToggleModule,
		MatCardModule,
		MatButtonModule,
		MatMenuModule,
		MatDialogModule,
		MatSelectModule,
		MatInputModule,
		MatCheckboxModule,
		MatExpansionModule,
		MatRadioModule,
		MatGridListModule,
		MatSnackBarModule,
		MatProgressBarModule,
		MatChipsModule,
		MatTooltipModule,
		MatTableModule
	],
	declarations: []
})
export class MaterialModule { }
