export enum AssignmentType {
	TPO_READING = "TPO_READING",
	TPO_LISTENING = "TPO_LISTENING",
	TPO_SPEAKING = "TPO_SPEAKING",
	TPO_INDEPENDENT_WRITING = "TPO_INDEPENDENT_WRITING",
	TPO_INTEGRATED_WRITING = "TPO_INTEGRATED_WRITING",
	VOCABULARY_ASSIGNMENT = "VOCABULARY_ASSIGNMENT"
}